apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*.yaml
      - ./infrastructure/k8s-development/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        infer: ["**/*"]
    - image: client
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        infer: ["**/*"]
    - image: tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        infer: ["**/*"]
    - image: orders
      context: orders
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        infer: ["**/*"]
    - image: expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        infer: ["**/*"]
    - image: payments
      context: payments
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        infer: ["**/*"]
