apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests: ["./infrastructure/k8s/*.yaml"]
build:
  local:
    push: false
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: client
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - dest: .
            src: "**/*.js"
    - image: tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync:
        manual:
          - dest: .
            src: "**/*.ts"
